#! /bin/bash

#This Script Allows The User To Browse Online Anonymously Through Various Web Proxies. First,  Has The User Enter 5 IP's That Belong To Web Proxies In Other Coutries. Script Then Adds These IP's To The 'proxychains.conf' file and starts a browser through the IP's Entered. 

#Usage Method
usage() {
        echo "Usage: [PROGRAM_NAME]"
}

#Exit Function
exit_func() {

	if [ $1 == 1 ]; then
		echo "Incorrect Number Of Arguments. Exiting..."
		usage
		exit 1
	fi
}

#Print Initial Statements, Open Webpage To Get Proxy IP's From Other Countries
echo "Please Complete The Following To Start Anonymous Browsing..."
echo ""
echo "Edit '/etc/proxychains.conf' file. Comment out line 18 which reads 'strict_chain' and uncomment line 39 which reads 'random_chain'. This Establishes Each Proxy Connection Randomly." 
echo ""
echo "Choose 5 'High Anonymity' Proxys From Following Site..."
echo  "Make Sure You Choose Proxys With Port '8080'"
echo ""
gnome-terminal -e "firefox -private-window http://www.samair.ru/proxy-by-country/Russian-Federation-01.htm"
sed -i "/http*/d" /etc/proxy_list
sed -i "/http*/d" /etc/proxychains.conf

#Asks User To Enter 5 Proxy Servers and Adds IP's To proxy_list
for i in {1..5}
do
	if [ $i -eq 1 ]; then
		echo "Enter Proxy IP In Form: xxx.xxx.xxx.xxx:8080"
	fi

	printf "Press 'Enter' When Finished. \n"
	printf "Enter Proxy $i: "
	read proxy_ip
	printf "http $proxy_ip" >> /etc/proxy_list
done

#Append 'proxy_list' IP's To The End Of 'proxychains.conf' file. 
sed -i "/http*/d" /etc/proxychains.conf
cat /etc/proxy_list >> /etc/proxychains.conf
echo "Done."

echo "Starting $1 Through Anonymous Proxy..."
proxychains $1 
