#! /bin/bash

#Usage Function
usage() {
        echo "Usage: [PROGRAM_NAME]"
}

#Exit Function
exit_func() {
        if [ "$1" -eq 1 ]; then
                echo "Exit 1 --> Wrong Number of Arguments."
                exit 1
        elif [ "$1" -eq 0 ]; then
                echo "Exit 0 --> Success!"
                exit 0
	elif [ "$1" -eq 2 ]; then
		echo "Exit 2 --> Not Connected To Home Group Shared Folder."
		exit 2
        fi
}

#Function That Actually Creates The Backup of The Files Of Your Choosing
backup(){
	
	tar -cpf /path/of/save/location/`date +%F`.tar /path/of/files/to/save/* > /dev/null 2>&1 
	#Can Exclude Files By Adding: --exclude /path/of/file/to/exclude

	#Find Past Backups And Delete Them, Send Any Messages To /dev/null
        find /path/to/current/backups/* -mtime +1 -exec rm {} \; > /dev/null 2>&1
}

#If Correct Number Of Arguments Run Program
#Else Print Usage And Exit
if [ "$#" -eq 0 ]; then
	
	#Check If Outside Hard-Disk Is Mounted, Save Error Result
	ls /path/to/current/backups > /dev/null 2>&1
	result=$?
	
	#If Hard-Disk Is Not Mounted, Mount/SSHFS To Host, Backup Data, Unmount, Exit
	#If Hard-Disk Is Already Mounted, Backup Data, Unmount, Exit
	#Else, Pring Usage, Exit
	if [ $result -eq 2 ]; then
		sshfs user@"your_ip_address":/disk_name /disk_name
		backup
		umount /hard_disk
                exit_func 0
	elif [ $result -eq 0 ]; then
		backup
		umount /hard_disk
                exit_func 0
	else
		usage
		exit_func 2
	fi

else
        usage
        exit_func 1
fi
