#! /bin/bash

#This Script Sets Up VPN and SSH connection back to home machines

#Usage Method
usage() {
	echo "Usage: [PROGRAM_NAME] [OPTION]"
	echo "Usage: OPTIONS: [ -h | --home ] [ -k | --kvm ]"
}

check_args () {
	
	if [ "$#" != 1 ]; then
		usage
		exit_func 1
	elif [ "$#" == 1 ]; then
		return 0
	fi
}

#Exit Script Function
exit_func () {

        if [ $1 == 1 ]; then
                echo "Exit 1 --> Incorrect Number Of Arguments."
                exit 1
        elif [ $1 == 2 ]; then
                echo "Exit 2 --> VPN Connection Could Not Be Established"
                exit 2
	elif [ $1 == 3 ]; then
		echo "Exit 3 --> Unable To Break Connection"
		exit 3
        elif [ $1 == 0 ]; then
                echo "Exit 0 --> Success!"
		exit 0
        fi
}

#Method to establish vpn connection
establish_connection () {

	gnome-terminal -e "openvpn --config /root/Documents/rictopVPN/rictop.ovpn"

	#If Loop to Check Connection Status
	if [ !"$(check_connection)" ]; then
		usage
		exit_func 2
	elif [ "$(check_connection)" ]; then 
		return 0
	fi
}

#Check Connection Method Tests Connection status
check_connection () {		
	
	#Testing if I Can Ping To A Computer I Know To Be UP and On My Network
	#Returns Exit Status of Ping Command
	for i in 1 2
	do
		ping -c3 123.456.7.890
		res=$?

		if [ $res == 0 ]; then 
			return $res
		else
			continue
		fi
	done
}

#Break Connection Method To Kill All openvpn Processes
break_connection () {

	killall openvpn
	return 0
}

#If There Are Enough Arguments
if [ "$(check_args)" ]; then
	#While There Are Command Line Arguments
	while [ "$1" != "" ]; do
		#Switch On Option Argument
		case $1 in
			-h | --home )	if [ "$(establish_connection)" ]; then
							ssh eric@home
							break_connection
							exit_func 0
						elif [ !"$(establish_connection)" ]; then
							usage
							exit_func 2
						fi
						;;

			-vm | --kvm ) 	if [ "$(establish_connection)" ]; then
							ssh root@kvm
							break_connection
							exit_func 0
						elif [ !"$(establish_connection)" ]; then
							usage
							exit_func 2
						fi
						;;

			* )			usage
						exit_func 2
		esac
	done
fi
